package com.citiustech.mrr;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ManualChaseBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "cpmm")
	private com.citiustech.mrr.CPMM1 cpmm;
	@org.kie.api.definition.type.Label(value = "parentProcessID")
	private java.lang.String parentProcessID;

	public ManualChaseBO() {
	}

	public com.citiustech.mrr.CPMM1 getCpmm() {
		return this.cpmm;
	}

	public void setCpmm(com.citiustech.mrr.CPMM1 cpmm) {
		this.cpmm = cpmm;
	}

	public java.lang.String getParentProcessID() {
		return this.parentProcessID;
	}

	public void setParentProcessID(java.lang.String parentProcessID) {
		this.parentProcessID = parentProcessID;
	}

	public ManualChaseBO(com.citiustech.mrr.CPMM1 cpmm,
			java.lang.String parentProcessID) {
		this.cpmm = cpmm;
		this.parentProcessID = parentProcessID;
	}

}